### ISSUE TITLE
Modulize all the things

### ISSUE THREAD

**Issue by trygve-lie** [webrebels/tba.js#4]
We should break this module into smaller reusable modules. Question is; multiple repos? Mono repo? How do we optimize for tree-shaking? Maybe we should look at https://lernajs.io/

Will be a large task doing this though.

**Comment by yoshuawuyts** [comment]
I think before we refactor all the thing, we should start to benchmark:
- file size (network and on-disk)
- download throughput (e.g. can we tree-shake bytes?)
- cyclic complexity
- possibility of HDD corruption

These are all very important, we should not refactor before we have data on this

**Comment by digitalsadhu** [comment]
I agree. I suspect the size of the project necessitates forming a committee. I'm a bit swamped stabilising the API surface, is anyone keen to head up a team that can look into finding the best people to form a committee?
